### ISSUE TITLE
obd cluster display[ERROR] Failed to connect oceanbase-ce

### ISSUE THREAD

**Issue by scott-wong** [oceanbase/obdeploy#5]
OS:Red Hat Enterprise Linux Server release 7.5 (Maipo)
Linux eu-server1 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

部署单节点成功`obd cluster deploy local -c mini-local-example.yaml
`
![image](https://user-images.githubusercontent.com/1947609/120416179-504e9900-c38f-11eb-9334-9da851699518.png)

启动几分钟后
再执行`obd cluster display oceanbase`
报错`[ERROR] Failed to connect oceanbase-ce`
observer本身没问题，可以用mysql客户端连接。
/root/.obd/log/obd日志
`[2021-06-02 10:39:46] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] -- exited code 0
[2021-06-02 10:39:46] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] - sub status ref count to 0
[2021-06-02 10:39:46] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] - export status
[2021-06-02 10:39:46] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] - Call oceanbase-ce-py_script_connect-3.1.0 for oceanbase-ce-3.1.0-56f57e9843e719d830ec03c206d914f4b3adc82b
[2021-06-02 10:39:46] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] - import connect
[2021-06-02 10:39:46] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] - add connect ref count to 1
[2021-06-02 10:39:46] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [INFO] Connect to observer
[2021-06-02 10:40:16] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] - sub connect ref count to 0
[2021-06-02 10:40:16] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [DEBUG] - export connect
[2021-06-02 10:40:16] [ca36f8aa-c34b-11eb-a39a-5897bde6551a] [ERROR] [ERROR] Failed to connect oceanbase-ce`

**Comment by frf12** [comment]
请提供下`cat /root/.obd/cluster/oceanbase/config.yaml`和`mysql -h127.1 -uroot -P2883 -e "select * from oceanbase.__all_server;"`的执行结果

**Comment by scott-wong** [comment]
之前是mini-local-example.yaml的默认配置，出现Failed to connect oceanbase-ce问题后我又按local-example.yaml配置改了下，还是同样问题。
```
cat /root/.obd/cluster/oceanbase/config.yaml

oceanbase-ce:
  servers:
    # Please don't use hostname, only IP can be supported
    - 192.168.0.42
  global:
    home_path: /data/observer
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: enp2s0f0
    mysql_port: 2883
    rpc_port: 2882
    zone: zone1
    cluster_id: 1
    #datafile_size: 8G
    # please set memory limit to a suitable value which is matching resource. 
    memory_limit: 32G
    #system_memory: 4G
    #stack_size: 512K
    #cpu_count: 16
    #cache_wash_threshold: 1G
    #__min_full_resource_pool_memory: 268435456
    #workers_per_cpu_quota: 10
    #schema_history_expire_time: 1d
    # The value of net_thread_count had better be same as cpu's core number. 
    #net_thread_count: 4
    #sys_bkgd_migration_retry_num: 3
    #minor_freeze_times: 10
    #enable_separate_sys_clog: 0
    #enable_merge_by_turn: FALSE
    datafile_disk_percentage: 20
user:
  username: root
  password: ***
```

![image](https://user-images.githubusercontent.com/1947609/120423730-94489a80-c39d-11eb-862d-2b7ce97fff55.png)
