### ISSUE TITLE
升级obproxy异常

### ISSUE THREAD

**Issue by tuitang00** [oceanbase/obdeploy#83]
obproxy 从3.1.0升级3.2.0失败
Connect to obproxy x
```
Get local repositories and plugins ok
+---------------------------------------------------------------------------------------------------------+
|                    Search obproxy 3.2.0 Result                    |
+---------+---------+---------+--------+------------------------------------------------------------------+
| name  | version | release | arch  | md5                               |
+---------+---------+---------+--------+------------------------------------------------------------------+
| obproxy | 3.2.0  | 1.el7  | x86_64 | c2ad988860a0fe5c07cbe3755fab0e2c165cf7a771e6c1f11741cc7208bf13d3 |
+---------+---------+---------+--------+------------------------------------------------------------------+
Download obproxy-3.2.0-1.el7.x86_64.rpm (7.80 M): 100% [####################################################################################] Time: 0:00:05  1.38 MB/s
install obproxy-3.2.0 for local ok
Open ssh connection ok
[WARN] No such upgrade_route plugin for obproxy-3.1.0
[WARN] No such upgrade_check plugin for obproxy-3.1.0
[WARN] No such upgrade_check plugin for obproxy-3.2.0
+-----------------------------------------------------------------------------------------+
|                 Packages Will Be Used                 |
+---------+---------+---------+--------+------------------------------------------+-------+
| name  | version | release | arch  | md5                   | mark |
+---------+---------+---------+--------+------------------------------------------+-------+
| obproxy | 3.1.0  | 1.el7  | x86_64 | 0b17cf0459a3b53c5a2febb6572894d183154c64 | start |
| obproxy | 3.2.0  | 1.el7  | x86_64 | 8d5c6978f988935dc3da1dbec208914668dcf3b2 | dest |
+---------+---------+---------+--------+------------------------------------------+-------+
If you use a non-official release, we cannot guarantee a successful upgrade or technical support when you fail. Make sure that you want to use the above package to upgrade. [y/n]: y
Remote obproxy-3.2.0-8d5c6978f988935dc3da1dbec208914668dcf3b2 repository install ok
Remote obproxy-3.2.0-8d5c6978f988935dc3da1dbec208914668dcf3b2 repository lib check ok
Stop obproxy ok
Start obproxy ok
obproxy program health check ok
Connect to obproxy x	
```

配置文件如下

```
oceanbase-ce:
  servers:
    - 192.168.1.3
  global:
    home_path: /root/observer
    devname: eth0
    mysql_port: 2881
    rpc_port: 2882
    zone: zone1
    cluster_id: 1
    memory_limit: 8G
    system_memory: 4G
    stack_size: 512K
    cpu_count: 16
    cache_wash_threshold: 1G
    __min_full_resource_pool_memory: 268435456
    workers_per_cpu_quota: 10
    schema_history_expire_time: 1d
    net_thread_count: 4
    major_freeze_duty_time: Disable
    minor_freeze_times: 10
    enable_separate_sys_clog: 0
    enable_merge_by_turn: FALSE
    datafile_disk_percentage: 20
    syslog_level: INFO
    enable_syslog_recycle: true
    max_syslog_file_count: 4
    appname: observer_cluster_name
obproxy:
  servers:
    - 192.168.1.2
  global:
    listen_port: 2883
    prometheus_listen_port: 2884
    home_path: /root/obproxy
    rs_list: 192.168.1.3:2881
    enable_cluster_checkout: false
    cluster_name: observer_cluster_name
```
